services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      ENCRYPTION: $(openssl rand -hex 32) # Generates a 32-byte key
    volumes:
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
